all: diagonal horizontal spirals

diagonal: 
	gcc Code/diagonal.c -lm -o diagonal

horizontal: 
	gcc Code/horizontal.c -lm -o horizontal

spirals: 
	gcc Code/spirals.c -lm -o spirals
	
clean:
	rm diagonal horizontal spirals
